blogapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path , include
from blogapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),

    path('new/', views.new, name = 'new'),
    path('create/', views.create, name = 'create'),

    path('formcreate/', views.formcreate, name = 'formcreate'),

    path('modelformcreate/', views.formcreate, name = 'modelformcreate'),

    path('blogapp/', include('blogapp.urls')), 

    path('common/', include('common.urls')),

    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]   

blogapp/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

common/models.py
from django.db import models

# Create your models here.

blogapp/forms.py
from dataclasses import fields
from msilib.schema import File
from django import forms
from .models import Blog

# 모델이 나중에 결정됨 (views.py 의 메소드 실행시에) => 어떤 모델을 기반으로 form 을 만들지 결정되어 있지 않음
class BlogForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField(widget = forms.Textarea)

# 모델이 현재 바로 이미 결정됨 => 애초에 form 의 존재가 모델을 기반으로 함
class BlogModelForm(forms.ModelForm):
    class Meta:
        model = Blog
        # fields = '__all__'
        fields = ['title', 'body']

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

blogapp/views.py
from django.shortcuts import render, redirect
from .models import Blog
from django.utils import timezone
from .forms import BlogForm, BlogModelForm

# Create your views here.

def home(request):
    return render(request, 'index.html')

def new(request):
    return render(request, 'new.html')

def create(request):
    if(request.method == 'POST'):
        post = Blog()
        post.title = request.POST['title']
        post.body = request.POST['body']
        post.date = timezone.now()
        post.save()
    return redirect('home')

def formcreate(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            post = Blog()
            post.title = form.cleaned_data['title']
            post.body = form.cleaned_data['body']
            post.save()
            return redirect('home')
    else:
        form = BlogForm()
    return render(request, 'form_create.html', {'form' : form})


def modelformcreate(request):
    if request.method == 'POST':
        form = BlogModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = BlogModelForm()
    return render(request, 'form_create.html', {'form' : form})

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

blogapp/templates/common/login.html
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

blogapp/templates/common/signup.html
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

blogapp/templates/form_create.html
<h1>django form 을 이용한 새 글 작성 페이지</h1>
<form action = "" method = "POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value = "새 글 작성하기">
</form>

blogapp/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

blogapp/templates/index.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <style>
        * {
            margin:0;
        }
        
        /* Header */
            header {
                display:flex;
                justify-content:center;
                align-items:center;
                padding:10px;
                height:30px;
                background-color:rgb(174, 211, 150);
            }
            .left-header {
                flex:1;
            }
            .main-header {
                flex:1;
                align-items:center;
                justify-content:center;
                display:inline-block;
                text-align:center;
                color:black;
            }
            a, a:link, a:visited {
                text-decoration:none;
                color:black;
            }
            .right-header {
                flex:1;
                float:right;
                text-align:right;
            }
        /* End of Header */
    
        /* Content-wrapper */
            div.content-wrapper {
                display:contents;
                float:left;
                height:2000px;
            }
            span {
                margin:10px;
                padding:10px;
            }
        /* End of Content-wrapper */
    </style>
   
    <title>Hello, mbti!</title>
</head>
<body>
<!-- Header -->
<header>
    <div class="left-header"></div>
    <div class="main-header"><a href="{% url 'login' %}">MBTI world</a></div>
    <div class="right-header">
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
        {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% endif %}
    </div>
</header>
<!-- End of Header -->

<li>
    {% if not user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
    {% endif %}
</li>

<div class="wrapper">
    <!-- Content Wrapper -->
	<div class="content-wrapper">
		<a href = "{% url 'new' %}" style="padding-left:40px;">html form 을 이용한 새 글 작성</a>&nbsp;
		<a href = "{% url 'formcreate' %}">django form 을 이용한 새 글 작성</a>&nbsp;
		<a href = "{% url 'modelformcreate' %}">django model form 을 이용한 새 글 작성</a>
		<hr>
				
	</div>
</div>
<!-- End of Content Wrapper -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

blogapp/templates/new.html
<form action = "{% url 'create' %}" method = "POST">
    {% csrf_token %}
    <div>
        <label for = "title">제목</label><br/>
        <input type = "text" name = "title" id = "title">
    </div>
    <div>
        <label for = "body">본문</label><br/>
        <textarea name = "body" id = "body" cols = "30" rows = "10"></textarea>
    </div>
    <input type="submit" value = "글 생성하기">
</form>